### ISSUE TITLE
Alternate regex syntax

### ISSUE THREAD

**Issue by ingydotnet** [yaml/yamlscript#114]
We have `/^.*\/foo\/bar.*$/` now which leads to leaning toothpick syndrome.

Clojure uses `#"^.*/foo/bar.*$"`.

We can't use that because it would be a yaml comment a most of the time.

We can use `\#"^.*/foo/bar.*$"` though.

We could also use `\"^.*/foo/bar.*$"`.

Python has ``r"^.*/foo/bar.*$"` so
we could use `\r"^.*/foo/bar.*$"`.

I like `\r"..."` because we could later make other kinds of strings with other letters.

**Comment by xanni** [comment]
Yes, I also like r/"..."

**Comment by mevanlc** [comment]
A bit off-topic because it's not YAML-related, but I -- also thinking of toothpick syndrome -- recently did a ranking of possible characters for an alternate regex delimiter for GitHub search. (Btw, did you know you can use regex in GitHub search? It's neat!). https://github.com/orgs/community/discussions/114708

I'm not sure it has any relevance to this issue, but since people who know about toothpick syndrome *and* care enough about it to write posts about it, are possibly few and far between, I thought I'd risk a little off-topicness to say hi here anyway!

**Comment by ingydotnet** [comment]
@mevanlc Hi!

We resolved this quite nicely with `rx('^.*/.*\.yaml$')`.
Where `rx` is a stand library function we just added.
Also there already was one that did the same thing called `re-pattern`.
Both generate a regex pattern object from a string.

**Comment by mevanlc** [comment]
@ingydotnet That's a very pleasing syntax! Thanks for sharing -- I will be trying it out.

**Comment by ingydotnet** [comment]
@mevanlc `(msg =~ rx('escaping single quote shouldn''t be a problem'))` :)

YAML uses `''` to escape single quotes in single quoted strings.

YS does the same thing at the expression level.
