### ISSUE TITLE
asdf-yamlscript plugin

### ISSUE THREAD

**Issue by FeryET** [yaml/yamlscript#124]
Hello.

I have implemented an asdf plugin for yamlscript, since I use the asdf-vm heavily to keep track of my runtimes etc, and yamlscript seems like a very promising project to me.

Feel free to comment on this.

https://github.com/FeryET/asdf-yamlscript

**Comment by ingydotnet** [comment]
Thanks for doing this. I'm new to asdf but I got it installed and installed ys.

I see that it installs `ys` and `libyamlscript.so` under `~/.asdf/shims/`.

I'll consider updating the YS language bindings for to look for libyamlscript in that directory.
This would probably be a bigger win if asdf was a trusted solution for installing Python, Rust, Ruby etc modules.
Currently for any language binding, you need to install the binding module and libyamlscript separately.
With asdf you _might_ be able to do it in one command.

I was a bit surprised that I needed to run both:
```
asdf install yamlscript latest
asdf global yamlscript latest
```
to get the `ys` command to work. But that's not your fault unless you are a core asdf dev.

I was also surprised that `asdf list-all yamlscript` listed all yamlscript repo tags instead of all yamlscript repo releases.
Non-release tags won't install.

If there are things you'd like to add to yamlscript regarding asdf let me know. Or make a PR.

Thanks again.

**Comment by ingydotnet** [comment]
Sorry. I was trying to ask you:
* Is asdf a good way to install a Python module along with libyamlscript?
  * Also for Clojure, Java, Perl, Raku, Ruby and Rust (many more to come)
* Can you make `list-all` uses releases instead of tags?
* Why does asdf require me to run the global command?
  * Especially after I've installed yamlscript the first time and there is no possible ambiguity.

**Comment by FeryET** [comment]
> Sorry. I was trying to ask you:
> 
>     * Is asdf a good way to install a Python module along with libyamlscript?
>       
>       * Also for Clojure, Java, Perl, Raku, Ruby and Rust (many more to come)
> 
>     * Can you make `list-all` uses releases instead of tags?
> 
>     * Why does asdf require me to run the global command?
>       
>       * Especially after I've installed yamlscript the first time and there is no possible ambiguity.

Sorry for the late reply. I have to preface that I don't use `asdf`, but `mise`(https://github.com/jdx/mise) which is an `asdf` compatible tool that is much faster.

* asdf is a version manager, so if you can bundle your python module (or other dependencies) alongside the actual package, then why not? It's is also very good for compiled languages which output binaries like Rust, Go and etc. 
* Yeah I can do that. This `list-all` implementation is the default implemented by the template, and I haven't change it. I can change it to only count releases and not all tags/
* asdf has two seperation layers. One is actuall installations, and one is the runtime environments. It links them via shims, and you can have a `global` runtime, which uses in folders that it cannot infer runtime version (either via `.tool-version` file or tool specific files like `.python-version`).


In mise I simply run: `mise use -g <tool>@<version>` for first time installation if the tool is in the list of `asdf-plugins`.

**Comment by FeryET** [comment]
>     * Can you make `list-all` uses releases instead of tags?

So after a period of being utterly busy, I had the time to check this issue out, and the way the current `list-all` works is by getting the tags that start with 'v', which I think is your release tags as of now too.

**Comment by ingydotnet** [comment]
Closing this as I assume nothing more is needed from us.
